= jython-cli
:source-highlighter: highlight.js

Article https://medium.com/@werner.fouche/running-jython-scripts-with-jbang-using-a-java-helper-program-9ab9f8e35ddc[Running Jython scripts with JBang using a Java helper program] describe how a *Jython.java* helper program is used to resolve the Maven dependencies of Jython script *banner.py*.

.Jython.java
[source,java]
----
///usr/bin/env jbang "$0" "$@" ; exit $?

// Jython.java

//DEPS io.leego:banana:2.1.0
//DEPS org.python:jython-standalone:2.7.4
//JAVA 21

import org.python.util.jython;

public class Jython {

    public static void main(String[] args) {
        jython.main(args);
    }

}
----

.banner1.py
[source,python]
----
# banner1.py
from __future__ import print_function

import io.leego.banana.BananaUtils as BananaUtils
import io.leego.banana.Font as Font

text0 = "Jython 2.7"
text1 = BananaUtils.bananaify(text0, Font.STANDARD)

print(text1)
----

.Output from banner1.py
[source,bash]
----
$ jbang run Jython.java banner1.py
[jbang] Resolving dependencies...
[jbang]    io.leego:banana:2.1.0
[jbang]    org.python:jython-standalone:2.7.4
[jbang] Dependencies resolved
[jbang] Building jar for Jython.java...
      _       _   _                   ____   _____
     | |_   _| |_| |__   ___  _ __   |___ \ |___  |
  _  | | | | | __| '_ \ / _ \| '_ \    __) |   / /
 | |_| | |_| | |_| | | | (_) | | | |  / __/ _ / /
  \___/ \__, |\__|_| |_|\___/|_| |_| |_____(_)_/
        |___/
----

The purpose of the `jython-cli` program is to generate a Jython.java type program from dependency information (metadata) added to a Jython script.

== PEP-723 (Inline Script Metadata)

We took inspiration from https://peps.python.org/pep-0723/[PEP-723] and adopted its metadata format (TOML) to specify:

* Maven Central dependencies
* Java runtime options
* Version of Jython to use
* Version of Java (JDK) to use

The metadata information starts with `# /// jbang` and ends with `# ///`. Each line inbetween these two markers are stripped of the first two characters, and the rest of the line is assumed to be valid TOML data.

.banner2.py
[source,python]
----
#!/usr/bin/env jython-cli

# banner2.py

# /// jbang
# requires-jython = "2.7.4"
# requires-java = "21"
# dependencies = [
#   "io.leego:banana:2.1.0"
# ]
# [java]
#   runtime-options = ""
# [jython-cli]
#   debug = false
# ///

import sys

import io.leego.banana.BananaUtils as BananaUtils
import io.leego.banana.Font as Font

def main():
    print(sys.argv)

    text0 = "Jython 2.7"
    text1 = BananaUtils.bananaify(text0, Font.STANDARD)

    print(text1)

main()
----

.TOML data extracted from banner2.py
[source,toml]
----
requires-jython = "2.7.4"
requires-java = "21"
dependencies = [
  "io.leego:banana:2.1.0"
]
[java]
  runtime-options = ""
[jython-cli]
  debug = false
----

.File banner2_py.java generated by jython-cli from TOML data
[source,java]
----
///usr/bin/env jbang "$0" "$@" ; exit $?

// banner2_py.java

//DEPS io.leego:banana:2.1.0
//DEPS org.python:jython-slim:2.7.4
//JAVA 21

import org.python.util.jython;

public class banner_py {

    public static void main(String[] args) {
        System.setProperty("python.console.encoding", "UTF-8");
        jython.main(args);
    }

}
----

== Jython script execution

Below can we can see how script banner2.py is executed after banner2_py.java is generated jython-cli and compiled and run by JBang.

.Running banner2.py using jython-cli
[source,bash]
----
$ jbang run jython-cli@jython banner2.py 1 2 3
[jbang] Building jar for banner2_py.java...
['banner2.py', '1', '2', '3']
      _       _   _                   ____   _____
     | |_   _| |_| |__   ___  _ __   |___ \ |___  |
  _  | | | | | __| '_ \ / _ \| '_ \    __) |   / /
 | |_| | |_| | |_| | | | (_) | | | |  / __/ _ / /
  \___/ \__, |\__|_| |_|\___/|_| |_| |_____(_)_/
        |___/

----

Steps::

$ `jbang run jython-cli@jython banner2.py 1 2 3`
* File banner2_py.java is generated by jython-cli from metadata extracted from banner2.py
* jython-cli then runs banner2.py using banner2_py.java
** $ `jbang run banner2_py.java banner2.py 1 2 3`

